### ISSUE TITLE
Not consistent output for phase 2

### ISSUE THREAD

**Issue by quiquegurdiel** [klacourse/MODA_GC#1]
I am able to merge the code and execute it with no issue in matlab. I have acess to the MASS database so I can obtain the tall vector for both the signal and the group consensus labels.

I have no issue regarding the phase 1 data. I obtain a EEGvector and a GCVect both of dimension 4657905 with the NaN values located in the same positions. From this data I am able to extract 404 excerpts of 115s both for the EEG signals and the labels, all as expected. I have explored this data and the labels make sense too.

The issue I have is regarding the phase 2 data. In this case I obtain a EEGvector longer than expected, of dimension 8625749, while the corresponding GCVect is considerably shorter, of dimension 3967845. My guess is the error occurs in the creation of the EEGvector because it starts with a quite long sequence of NaNs but removing them does not lead to the appropriate dimension. Also, I am able to retrieve the 345 excerpts of 115s expected from the GCVect so that part seems correct. But that is not the case for the EEGVector.

I leave an attachment of the plot EEGvector obtained for phase 2, the one saved in the file EEGVect_p2 (under \MODA02_pack\20230831_112835.m\output) after execution of the code. Hopefully you have come to a similar bug before and are able to help me obtaining the actual signal excerpts for phase 2.

![untitled](https://github.com/klacourse/MODA_GC/assets/65571266/26332a69-2d55-4d6f-b6b4-933218d0e0a4)

Kudos for the great work!

**Comment by klacourse** [comment]
Hi Enrique,
I did not encounter this problem when generating the EEG vector. Other teams have also succeeded without any problems. Could you send me the code you created on your side?  I will try to help you to the best of my knowledge.
Karine

**Comment by quiquegurdiel** [comment]
Thank you forthe quick response, Karine.

I have not edited the code. I have just replicated the issue following this steps.
1. Download the repository from the latest release.
2. Copy the PSG files to ./input/MASS_PSG
3. Execute MODA01_GC_DEF and MODA02_EEG_DEF

I attach the code that is saved for the execution, but I am afraid is the same one that is on your repository.
[code.zip](https://github.com/klacourse/MODA_GC/files/13218765/code.zip)

It is strange because threre are no errors and I see is the same logic used for both phases. I will debug it a bit further and come back to you with my findings.

**Comment by quiquegurdiel** [comment]
A quick update.

I have executed the code MODA02_genEEGVectBlock.m line by line setting the iPhase variable to 2.
In line 74 the EEGvector is initialised to NaNs with the expected size of 3967845.
In the loop starting in line 77 (for each subject) the EEG data is copied into the EEGvector. The size of the EEGvector at the end of each iteration it is growing, most likely unintentionally. It seems to me an issue with the indexing of where the data is pasted. How can it work for phase 1 and not for phase 2 is something still unclear to me.

Many thanks for the help. I will go slowly trough the logic of indexing and try to understand it deeper in the following days or weeks and come back to you if I clarify something further.

**Comment by klacourse** [comment]
The epoch number in the 7_segListSrcDataLoc_p2.txt file starts at 2026 instead of 1.
This is why the EEGVector has many NaNs at the beginning. However, the rest of the EEGVector should be valid.
I'm not currently set up to edit the code, validate and commit.
I will keep you informed of any updates.
Sorry for the trouble.

**Comment by quiquegurdiel** [comment]
Great! I have just edited the file 7_segListSrcDataLoc_p2.txt epoch number and it works now as expected. I have checked the signals and the annotations and it makes sense. I leave an attachment of the edited file, it might be useful if someone faces the same issue.

[7_segListSrcDataLoc_p2.txt](https://github.com/klacourse/MODA_GC/files/13236412/7_segListSrcDataLoc_p2.txt)

Thank you, Karine.
